/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package infirmayregister;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Arjun Kothakota
 */
public class HomePage extends javax.swing.JFrame {

    /** Creates new form HomePage */
    public HomePage() {
        initComponents();
    }
    
    public HomePage(String message){
        initComponents();
        studentIDTF.setText(message);
        
        String studentID = studentIDTF.getText();
        String string = null;       
        Statement statement = null;
        ResultSet resultSet = null;
        
        try {

            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/infirmary";
            Connection connection = (Connection) DriverManager.getConnection(database, "root", "arjun");
            statement = (com.mysql.jdbc.Statement) connection.createStatement();
            String sql= "select * from students where StudentID= '" + studentID + "'";
            
            resultSet=statement.executeQuery(sql);
            if(resultSet.next()){
                String studentName = resultSet.getString("studentName");
                String classAndSection = resultSet.getString("Class_Section");
                String board = resultSet.getString("Board");
                
                //String image= resultSet.getString("image");
                
                studentNameTF.setEnabled(true);
                classTF.setEnabled(true);
                boardTF.setEnabled(true);                
                
                
                //imageLbl.setEnabled(true);
                
                studentNameTF.setText(studentName);
                classTF.setText(classAndSection);
                boardTF.setText(board);
                
                
                                             
            }
            resultSet.close();
            statement.close();
            connection.close();
            
            
        }
        catch(Exception e){
            System.out.println("The catch is activated.");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentInfoBtn = new javax.swing.JLabel();
        pastiVisitsBtn = new javax.swing.JLabel();
        emailBtn = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        studentNameTF = new javax.swing.JTextField();
        studentIDTF = new javax.swing.JTextField();
        classTF = new javax.swing.JTextField();
        boardTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1385, 830));
        setMinimumSize(new java.awt.Dimension(1385, 830));
        setPreferredSize(new java.awt.Dimension(1385, 830));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentInfoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                studentInfoBtnMouseReleased(evt);
            }
        });
        getContentPane().add(studentInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 200, 260));

        pastiVisitsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pastiVisitsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pastiVisitsBtnMouseReleased(evt);
            }
        });
        getContentPane().add(pastiVisitsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 210, 260));

        emailBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emailBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                emailBtnMouseReleased(evt);
            }
        });
        getContentPane().add(emailBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 200, 260));

        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutBtnMouseReleased(evt);
            }
        });
        getContentPane().add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 80, 90, 40));

        studentNameTF.setEditable(false);
        studentNameTF.setBorder(null);
        studentNameTF.setOpaque(false);
        getContentPane().add(studentNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 590, 220, 40));

        studentIDTF.setEditable(false);
        studentIDTF.setBorder(null);
        studentIDTF.setOpaque(false);
        getContentPane().add(studentIDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 220, 40));

        classTF.setEditable(false);
        classTF.setBorder(null);
        classTF.setOpaque(false);
        getContentPane().add(classTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 650, 220, 40));

        boardTF.setEditable(false);
        boardTF.setBorder(null);
        boardTF.setOpaque(false);
        getContentPane().add(boardTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 650, 220, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/arjun/images/Home Page Layout.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1378, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentInfoBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentInfoBtnMouseReleased
                StudentInfo studentInfoPage= new StudentInfo();
                String studentID= studentIDTF.getText();                              
                new StudentInfo(studentID).setVisible(true);
                this.dispose();
    }//GEN-LAST:event_studentInfoBtnMouseReleased

    private void pastiVisitsBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pastiVisitsBtnMouseReleased
                String studentID = studentIDTF.getText();                              
                new PastVisits(studentID).setVisible(true);
                this.dispose();
    }//GEN-LAST:event_pastiVisitsBtnMouseReleased

    private void emailBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailBtnMouseReleased
                new Email(studentIDTF.getText()).setVisible(true);
                this.dispose();
    }//GEN-LAST:event_emailBtnMouseReleased

    private void logoutBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseReleased
                new StudentLogin().setVisible(true);
                this.dispose();
    }//GEN-LAST:event_logoutBtnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boardTF;
    private javax.swing.JTextField classTF;
    private javax.swing.JLabel emailBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel pastiVisitsBtn;
    private javax.swing.JTextField studentIDTF;
    private javax.swing.JLabel studentInfoBtn;
    private javax.swing.JTextField studentNameTF;
    // End of variables declaration//GEN-END:variables

}
