/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package infirmayregister;

import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Arjun Kothakota
 */
public class StudentLogin extends javax.swing.JFrame {

    /** Creates new form StudentLogin */
    public StudentLogin() {
        initComponents();
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();
        logoutLbl = new javax.swing.JLabel();
        proceedLbl = new javax.swing.JLabel();
        studentIDTF = new javax.swing.JTextField();
        visitsLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jOptionPane1.setMaximumSize(new java.awt.Dimension(500, 500));
        jOptionPane1.setMinimumSize(new java.awt.Dimension(500, 500));
        jOptionPane1.setPreferredSize(new java.awt.Dimension(500, 500));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutLblMouseReleased(evt);
            }
        });
        getContentPane().add(logoutLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 240, 40));

        proceedLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proceedLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                proceedLblMouseReleased(evt);
            }
        });
        getContentPane().add(proceedLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 640, 240, 50));

        studentIDTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        studentIDTF.setBorder(null);
        studentIDTF.setOpaque(false);
        studentIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDTFActionPerformed(evt);
            }
        });
        studentIDTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                studentIDTFKeyPressed(evt);
            }
        });
        getContentPane().add(studentIDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 280, 40));

        visitsLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        visitsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                visitsLblMouseReleased(evt);
            }
        });
        getContentPane().add(visitsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 240, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/arjun/images/Student Login layout.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLblMouseReleased
        Login loginForm= new Login();
        loginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutLblMouseReleased

    private void proceedLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedLblMouseReleased
        String studentID= studentIDTF.getText();
        String string=null;
        Statement statement=null;
        ResultSet resultSet= null;
        
        try {

            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/infirmary";
            Connection connection = (Connection) DriverManager.getConnection(database, "root", "arjun");
            statement = (com.mysql.jdbc.Statement) connection.createStatement();
            String sql= "select * from students where StudentID= '" + studentID + "'";
            
            resultSet = statement.executeQuery(sql);
            resultSet.next();
            string = resultSet.getString("studentID");
            resultSet.close();
            statement.close();
            connection.close();
            
            if(string.equalsIgnoreCase(studentID)){
                HomePage homePage= new HomePage();
                studentID= studentIDTF.getText();                              
                new HomePage(studentID).setVisible(true);
                this.dispose();
            } else if(string.equalsIgnoreCase(studentID)){
                jOptionPane1.showMessageDialog(rootPane, "Please check for Capital Case");
            }
            
            
        }
        catch(Exception e){        
            studentIDTF.setText("");
            jOptionPane1.showMessageDialog(rootPane, "This is an invalid Student ID");
        }
    }//GEN-LAST:event_proceedLblMouseReleased
    
    private void studentIDTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIDTFKeyPressed
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
        String studentID= studentIDTF.getText();
        String string=null;
        Statement statement=null;
        ResultSet resultSet= null; 
        
        try {

            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/infirmary";
            Connection connection = (Connection) DriverManager.getConnection(database, "root", "arjun");
            statement = (com.mysql.jdbc.Statement) connection.createStatement();
            String sql= "select * from students where StudentID= '" + studentID + "'";
            
            resultSet = statement.executeQuery(sql);
            resultSet.next();
            string = resultSet.getString("studentID");
            resultSet.close();
            statement.close();
            connection.close();
            
            if(string.equals(studentID)){
                HomePage homePage= new HomePage();
                studentID= studentIDTF.getText();                              
                new HomePage(studentID).setVisible(true);
                this.dispose();
            } else if(string.equalsIgnoreCase(studentID)){
                jOptionPane1.showMessageDialog(rootPane, "Please check for Capital Case");
            }
            
        }
        catch(Exception e){
                studentIDTF.setText("");
                jOptionPane1.showMessageDialog(rootPane, "This is an invalid Student ID");
            }  
        }
    }//GEN-LAST:event_studentIDTFKeyPressed

    private void visitsLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitsLblMouseReleased
        StudentVisits studentVisitsFrame = new StudentVisits();
        studentVisitsFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_visitsLblMouseReleased

    private void studentIDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel logoutLbl;
    private javax.swing.JLabel proceedLbl;
    private javax.swing.JTextField studentIDTF;
    private javax.swing.JLabel visitsLbl;
    // End of variables declaration//GEN-END:variables

}
